name: Build and Release Extension

on:
  push:
    tags:
      - 'v*' # Run when tag matches v*, e.g., v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Tests
        run: xvfb-run -a npm test

      - name: Package Extension
        run: npm run build-vsix

      - name: Get Extension Version
        id: get-version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: VS Code Copilot Utils v${{ steps.get-version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            vscode-copilot-utils-*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
